language: objective-c
xcode_workspace: RCrashReporting.xcworkspace
xcode_scheme: Tests
osx_image: xcode9.4

cache:
  - bundler

before_install:
  - gem update fastlane --no-ri --no-rdoc --no-document
  - pod repo update

script: fastlane ci

after_success:
  - |
    set -e
    curl -sS https://codecov.io/bash > codecov

    # verify checksum
    VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2)
    for i in 1 256 512; do
      printf "SHA$i: "
      curl -sS "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep codecov | shasum -a $i -c
    done
  - bash codecov -f ./artifacts/coverage/cobertura.xml -X coveragepy -X gcov -X xcode
