# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    # Use env variables to set up config endpoint/key in order
    # to keep those items secret
    set_info_plist_value(path: "./Tests/Info.plist",
                         key: "RCRConfigAPIEndpoint",
                         value: ENV['RCR_CONFIG_ENDPOINT'] || "CONFIG_API_ENDPOINT")
    set_info_plist_value(path: "./Tests/Info.plist",
                         key: "RPTSubscriptionKey",
                         value: ENV['RCR_SUBSCRIPTION_KEY'] || "SUBSCRIPTION_KEY")

    update_project_team(
      path: "./Samples/CRDemoProject/CRDemoProject.xcodeproj",
      teamid: ENV['REM_FL_EXPORT_TEAM_ID'] || "UNDEFINED"
    )
    shared_sample(options)
    shared_tests(options)
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
